Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'

Style/FileName:
  Exclude:
  - 'Gemfile'
  - 'canonical-header.gemspec'

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRailsVersion: 5.1 
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'

