Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'
  - canonical-header.gemspec

Style/FileName:
  Exclude:
  - 'Gemfile'
  - 'canonical-header.gemspec'
  - lib/canonical-header.rb

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.1
  Include:
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
